name: color-bg
stageName: color-bg-stage
primaryName: color-bg-primary
host: istio-demo.harness.io
image: <+artifact.image>
splitTraffic: false

replicas: 2
namespace: <+infra.namespace>

frontend:
  uiPath: blue-green
  title: Blue / Green - Istio Traffic Shift
  image: us-docker.pkg.dev/sales-209522/demo/continuous-requests:100
